exports.SipMethods = {
    invite: 'INVITE',
    ack: 'ACK',
    bye: 'BYE',
    cancel: 'CANCEL',
    register: 'REGISTER',
    options: 'OPTIONS',
    prack: 'PRACK',
    subscribe: 'SUBSCRIBE',
    notify: 'NOTIFY',
    publish: 'PUBLISH',
    info: 'INFO',
    refer: 'REFER',
    message: 'MESSAGE',
    update: 'UPDATE',
}